dependencies:
  #  - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.6.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.0'

dotenv: .env
networks:
  default: ganache-testnet
  goerli:
    eth_usd_price_feed: "0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2"
    verify: True
  development:
    verify: False
  ganache-local5:
    verify: False
  ganache-testnet:
    verify: False

wallets:
  from_key: 165f321b77d0293c533a7f6eabc1fa7c4efdc5a644b3d6bc1e382cf848705ec8