dependencies:
  # the pattern is <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
network:
  development:
    mainnet-fork:
      eth-usd-price-feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
